### ISSUE TITLE
Implement PropertiesChanged signal for DBus properties

### ISSUE THREAD

**Issue by andyholmes** [bboozzoo/mconnect#12]
If the properties exported over DBus are annotated with `org.freedesktop.DBus.Property.EmitsChangedSignal` then PropertiesChanged will be emitted when a value has changed and redundant signals can be avoided. I've encountered several race conditions with KDE Connect where signals are emitted before the properties are updated, and this could help make property changes and signals more atomic.

[https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties](https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties)
[https://wiki.gnome.org/Projects/Vala/DBusServerSample#Service_with_D-Bus_property_change_notifications](https://wiki.gnome.org/Projects/Vala/DBusServerSample#Service_with_D-Bus_property_change_notifications)

**Comment by bboozzoo** [comment]
Yes, it's on my TODO list, although the Vala way of handling this is quite annoying.

**Comment by andyholmes** [comment]
I pulled your latest commit, seems to be working great.

**Comment by bil-elmoussaoui** [comment]
@bboozzoo What's still need to be implemented to have a fully working DBus API? Or is there a TODO list for this project? I would love to help so I can get rid of KDE Connect on my GNOME installation.

**Comment by andyholmes** [comment]
@bil-elmoussaoui As I understand it, the base protocol is complete (except for encryption which should be upgraded to TLS sockets eventually). Most of the work is just implementing the various plugins as public functions, then adding DBus annotations so they're exported.

**Comment by bboozzoo** [comment]
@bil-elmoussaoui there's no TODO yet :) but off the top my head the things to do are (in order of importance):
* merge `bboozzoo/dbus-support` to master (seems that people are using it right now and no major issues were reported)
* address #16 
* stabilize and merge `bboozzoo/dbus-support-fileshare` (it's working right now but only download from mobile is possible)
* add encryption for device channel in to-device direction (right now the host presents its key but there's no encrypted traffic going to mobile, only from-device direction is used, also it's a prerequisite for clipboard sharing)
* address #15 (though I support there's a need for clipboard sync plugin first, also not sure how it would play with wayland)
* poke @desiderantes I'd be happy to merge meson support he did (GNOME is migrating to meson anyway and major distros, even including Yocto/OE, support it out of the box) or maybe someone else would like to pick this up

**Comment by andyholmes** [comment]
> * add encryption for device channel in to-device direction (right now the host presents its key but there's no encrypted traffic going to mobile, only from-device direction is used, also it's a prerequisite for clipboard sharing)

It's worth pointing out MConnect uses v5 protocol right now while v7 supports TLS sockets, I think using the same paired PEM to make a certificate. Might be encrypted packets aren't a thing anymore, just sending over TLS after key exchange.

**Comment by desiderantes** [comment]
> - poke @desiderantes I'd be happy to merge meson support he did (GNOME is migrating to meson anyway and major distros, even including Yocto/OE, support it out of the box) or maybe someone else would like to pick this up

hahaha I didn't know you saw my fork! Besides the meson migration, I was just experimenting with the code (move the plugins to singletons, moved the notifications to GLib.Notification, etc.) and picking a consistent code style (I default to the valac code style). After you merge your branch I can rework some of these changes and send them as PRs.
