### ISSUE TITLE
Firefox tabs on phone

### ISSUE THREAD

**Issue by pietrondo** [bboozzoo/mconnect#2]
It is possible implement 

https://kamikazow.wordpress.com/2014/11/22/send-firefox-tabs-to-your-phone-via-kde-connect/

on mconnect?
Or is too early for this features?

Thx!

**Comment by bboozzoo** [comment]
Hey, that looks really interesting. I just looked at issue #3 from the author of indicator-kdeconnect asking about DBus interface. The way I see it DBus interface is essential for implementing what you ask for.

**Comment by bboozzoo** [comment]
Closing this for now. Firefox Sync provides similar functionality already.
