### ISSUE TITLE
Compile on Ubuntu

### ISSUE THREAD

**Issue by laurentdinclaux** [bboozzoo/mconnect#20]
I don't manage to find the proper apt repos dependency to build this. Can we have some guidance about it please?

**Comment by andyholmes** [comment]
This should get you going:

    sudo apt-get install autoconf libtool valac libgirepository1.0-dev libjson-glib-dev libgee-0.8-dev libssl-dev libnotify-dev libgtk-3-dev
    git clone https://github.com/bboozzoo/mconnect.git
    cd mconnect
    autoreconf -if
    ./configure --prefix=/usr
    make

Then you can run mconnect:

    ./mconnect -d

Or install as a package:

    sudo apt-get install checkinstall
    sudo checkinstall --type debian

And follow the prompts to change any package details you'd like. Fair warning this will take a little over 200MB of space. Let me know if I missed anything, `./configure` should catch it if I did.

**Comment by laurentdinclaux** [comment]
Thanks heaps!

**Comment by bboozzoo** [comment]
Actually it makes sense to provide example instructions somewhere. I'll add ubuntu builds to travis setup so that people can use it as reference.

**Comment by andyholmes** [comment]
Cool. It *should* always work, but it's worth mentioning the list I posted relies on dependency "recommends" chaining. I also added a markdown table based on your `travis.build` [to my Wiki here](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Installation#mconnect) you could copy to your readme if you wanted.
