### ISSUE TITLE
autotools to meson build - upgrade

### ISSUE THREAD

**Issue by okias** [bboozzoo/mconnect#23]
Hello guys,

I'd like to create Gentoo ebuild for mconnect (since I didn't found any). Before I'll start making it, would you guys consider moving to Meson build system [1] (as successor of automake ugly things?).

- In case you do, I'll wait little bit.
- If you not willing to do it, but you accept pull request, I can do it (it will take more time, but still good way to go)
- in scenario when you'll reject Meson work, I'll just create ebuild based on old autotools..

Thanks
David

[1] https://blogs.gnome.org/mclasen/2017/04/20/meson-considerations/

**Comment by bboozzoo** [comment]
I've recently pushed meson support to `bboozzoo/tls-support` branch. I plan to merge the branch later this week. 

BTW. I'll probably keep both autotools and meson in the tree for a while and then transition to meson only builds.

**Comment by bboozzoo** [comment]
Meson support is in master now.
