### ISSUE TITLE
MConnect gui

### ISSUE THREAD

**Issue by vikoadi** [bboozzoo/mconnect#3]
hello bboozzoo,
maybe its too early to ask, but how will mconnect daemon interact with  other gui program?
I suggest to have a dbus which compatible to kdeconnect
as reference i wrote some indicator for kdeconnectd (https://github.com/vikoadi/indicator-kdeconnect) which use kdeconnect's dbus to interact and i hope that mconnect will be as flexible as original kde-connect.
Thanks

**Comment by bboozzoo** [comment]
Sorry for late reply, been busy with work lately. I agree, DBus is the only reasonable solution for interacting with UI. I see that you already have an app that works with kdeconnectd DBus API, that's good. If anyone wants to contribute patches adding DBus interface to mconnect, I'd happily accept that.
