### ISSUE TITLE
Feature Request: GUI for MConnect

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [bboozzoo/mconnect#32]
Having the backend and CLI, is it possible to implement a GUI for the configuration? Similar to what the KDEConnect has.

**Comment by bboozzoo** [comment]
There's a Gnome Shell extension right here: https://github.com/andyholmes/gnome-shell-extension-mconnect Unfortunately I'm not aware of similar tools for other environments. However, the DBus API is all there and quite usable, so it should be quite easy to build something for your favorite environment.

**Comment by BeatLink** [comment]
Would it be possible to build an AppIndicator for it?
