### ISSUE TITLE
Cursor moves but does not show

### ISSUE THREAD

**Issue by layonsonofre** [bboozzoo/mconnect#36]
Hi!
First of all, thanks for the amazing app you have created!

I was testing the Remote Input and noticed that the cursor is moving, log shows the positions being updated, but the pointer on the screen does not change, it keeps in the same position. Clicks and keyboard works fine.
Do you have any idea of how can I debug this to try to find a solution?

Thanks!

**Comment by bboozzoo** [comment]
Thanks for reporting this. Are you using Xorg or wayland?

**Comment by layonsonofre** [comment]
Hi!
I am using wayland

**Comment by bboozzoo** [comment]
Unfortunately mconnect mousepad/keyboard support is limited by whatever AT-SPI supports. More details are provided in #14
