### ISSUE TITLE
mpris support

### ISSUE THREAD

**Issue by donRaphaco** [bboozzoo/mconnect#38]
I recently had some time, so I tried to implement the mpris functionality.
You can see my results [here](https://github.com/donRaphaco/mconnect/tree/mpris).
Don't know if you have planned implementing it, if so feel free to comment, edit, copy, pull.
I have no previous vala experience so I'm sure my code can be improved, but for me it works quite well.

**Comment by bboozzoo** [comment]
Thanks, this looks promising. Can you open a pull request?
