### ISSUE TITLE
Ubuntu compiling error

### ISSUE THREAD

**Issue by freeniki** [bboozzoo/mconnect#4]
Ubuntu 14.04 amd64

...
make[1]: Entering directory `/home/ubuntu/Downloads/mconnect-0.2'
  VALAC    mconnect_vala.stamp
src/core.vala:50.4-50.7: error: The name `info' does not exist in the context of `Core.instance'
			info("supported interfaces: %s", string.joinv(", ",
			^^^^
src/notification.vala:55.7-55.21: error: The name `match_string' does not exist in the context of `string?'
		if (id.match_string("com.android.dialer", false) == true)
		    ^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
make[1]: *** [mconnect_vala.stamp] Error 1
make[1]: Leaving directory `/home/ubuntu/Downloads/mconnect-0.2'
make: *** [all] Error 2
...
See full LOG:
http://pastebin.com/KNMMQsiG

**Comment by freeniki** [comment]
Solved:
Install new version vala from ppa:vala-team/ppa

**Comment by bboozzoo** [comment]
Can you indicate what Vala version worked for you? This might need an update in README

**Comment by freeniki** [comment]
valac-0.26 from ppa:vala-team/ppa
