### ISSUE TITLE
Another Ubuntu compilation problem

### ISSUE THREAD

**Issue by LissieTilbrook** [bboozzoo/mconnect#40]
According to the instructions provided by @andyholmes at https://github.com/bboozzoo/mconnect/issues/20 I run into a roadblock at this step:

`autoreconf -if`

Which then spits out this error:

`autoreconf: 'configure.ac' or 'configure.in' is required`

Which means... `File Not Found.`

So... what should I do? If `autoreconf` needs a `configure.ac` or `configure.in` file... I cannot do anything.

Please help

**Comment by bboozzoo** [comment]
I'm guessing the problem doesn't exist anymore. Please reopen if you still experience the issue.
