### ISSUE TITLE
build error on Manjaro 18.0.2

### ISSUE THREAD

**Issue by amitbha** [bboozzoo/mconnect#43]
../src/mconnect/device-proxy.vala:71.5-71.23: error: Property `DeviceDBusProxy.allowed' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool allowed {
    ^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:79.5-79.25: error: Property `DeviceDBusProxy.is_active' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool is_active {
    ^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:63.5-63.25: error: Property `DeviceDBusProxy.is_paired' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool is_paired {
    ^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:27.5-27.20: error: Property `DeviceDBusProxy.id' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public string id {
    ^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:35.5-35.22: error: Property `DeviceDBusProxy.name' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public string name {
    ^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:43.5-43.29: error: Property `DeviceDBusProxy.device_type' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public string device_type {
    ^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:51.5-51.32: error: Property `DeviceDBusProxy.protocol_version' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public uint protocol_version {
......
Compilation failed: 7 error(s), 30 warning(s)
[12/57] Compiling C object 'test-mconn-crypt@exe/meson-generated_src_crypt_certificate.c.o'.
ninja: build stopped: subcommand failed.

**Comment by dmaglio** [comment]
same issue in Fedora30

**Comment by bboozzoo** [comment]
Should be fixed in master now.
