### ISSUE TITLE
Error building on Arch.

### ISSUE THREAD

**Issue by dimeritium-foil** [bboozzoo/mconnect#45]
Gives me a whole bunch of errors when I run ninja and fails,

`[1/41] Compiling Vala source ../src/mconnect/main.vala ../src/mconnect/discovery.vala ../src/mconnect/packet.vala ../src/mconnect/device.vala ../src/mconnect/discovereddevice.vala ../src/mconnect/device-proxy.vala ../src/mconnect/devicemanager.vala ../src/mconnect/devicemanager-proxy.vala ../src/mconnect/devicechannel.vala ../src/mconnect/core.vala ../src/mconnect/packethandlerinterface.vala ../src/mconnect/packethandlerinterface-proxy.vala ../src/mconnect/packethandlers.vala ../src/mconnect/packethandlers-proxy.vala ../src/mconnect/notification.vala ../src/mconnect/battery.vala ../src/mconnect/battery-proxy.vala ../src/mconnect/telephony.vala ../src/mconnect/telephony-proxy.vala ../src/mconnect/mousepad.vala ../src/mconnect/ping.vala ../src/mconnect/ping-proxy.vala ../src/mconnect/config.vala ../src/mconnect/application.vala ../src/mconnect/utils.vala ../src/mconnect/property-proxy.vala ../src/mconnect/share.vala ../src/mconnect/share-proxy.vala ../src/mconnect/mpris.vala ../src/mconnect/mpris-proxies.vala ../src/mconnect/io-job.vala ../src/mconnect/transfer-manager.vala ../src/mconnect/transfer-manager-proxy.vala ../src/mconnect/transfer-interface.vala ../src/mconnect/transfer-proxy.vala ../src/mconnect/transfer-download.vala ../src/mconnect/transfer-upload.vala ../src/mconnect/logging.vala ../src/crypt/certificate.vala.
FAILED: mconnect@exe/src/mconnect/main.c mconnect@exe/src/mconnect/discovery.c mconnect@exe/src/mconnect/packet.c mconnect@exe/src/mconnect/device.c mconnect@exe/src/mconnect/discovereddevice.c mconnect@exe/src/mconnect/device-proxy.c mconnect@exe/src/mconnect/devicemanager.c mconnect@exe/src/mconnect/devicemanager-proxy.c mconnect@exe/src/mconnect/devicechannel.c mconnect@exe/src/mconnect/core.c mconnect@exe/src/mconnect/packethandlerinterface.c mconnect@exe/src/mconnect/packethandlerinterface-proxy.c mconnect@exe/src/mconnect/packethandlers.c mconnect@exe/src/mconnect/packethandlers-proxy.c mconnect@exe/src/mconnect/notification.c mconnect@exe/src/mconnect/battery.c mconnect@exe/src/mconnect/battery-proxy.c mconnect@exe/src/mconnect/telephony.c mconnect@exe/src/mconnect/telephony-proxy.c mconnect@exe/src/mconnect/mousepad.c mconnect@exe/src/mconnect/ping.c mconnect@exe/src/mconnect/ping-proxy.c mconnect@exe/src/mconnect/config.c mconnect@exe/src/mconnect/application.c mconnect@exe/src/mconnect/utils.c mconnect@exe/src/mconnect/property-proxy.c mconnect@exe/src/mconnect/share.c mconnect@exe/src/mconnect/share-proxy.c mconnect@exe/src/mconnect/mpris.c mconnect@exe/src/mconnect/mpris-proxies.c mconnect@exe/src/mconnect/io-job.c mconnect@exe/src/mconnect/transfer-manager.c mconnect@exe/src/mconnect/transfer-manager-proxy.c mconnect@exe/src/mconnect/transfer-interface.c mconnect@exe/src/mconnect/transfer-proxy.c mconnect@exe/src/mconnect/transfer-download.c mconnect@exe/src/mconnect/transfer-upload.c mconnect@exe/src/mconnect/logging.c mconnect@exe/src/crypt/certificate.c 
valac -C --debug --debug --vapidir /home/farris/Downloads/mconnect/vapi --pkg posix --pkg gtk+-3.0 --pkg posix --pkg gnutls --pkg atspi-2 --pkg gdk-3.0 --pkg libnotify --pkg gee-0.8 --pkg json-glib-1.0 --pkg gio-unix-2.0 --pkg gio-2.0 --pkg gobject-2.0 --pkg glib-2.0 --color=always --directory mconnect@exe --basedir ../ ../src/mconnect/main.vala ../src/mconnect/discovery.vala ../src/mconnect/packet.vala ../src/mconnect/device.vala ../src/mconnect/discovereddevice.vala ../src/mconnect/device-proxy.vala ../src/mconnect/devicemanager.vala ../src/mconnect/devicemanager-proxy.vala ../src/mconnect/devicechannel.vala ../src/mconnect/core.vala ../src/mconnect/packethandlerinterface.vala ../src/mconnect/packethandlerinterface-proxy.vala ../src/mconnect/packethandlers.vala ../src/mconnect/packethandlers-proxy.vala ../src/mconnect/notification.vala ../src/mconnect/battery.vala ../src/mconnect/battery-proxy.vala ../src/mconnect/telephony.vala ../src/mconnect/telephony-proxy.vala ../src/mconnect/mousepad.vala ../src/mconnect/ping.vala ../src/mconnect/ping-proxy.vala ../src/mconnect/config.vala ../src/mconnect/application.vala ../src/mconnect/utils.vala ../src/mconnect/property-proxy.vala ../src/mconnect/share.vala ../src/mconnect/share-proxy.vala ../src/mconnect/mpris.vala ../src/mconnect/mpris-proxies.vala ../src/mconnect/io-job.vala ../src/mconnect/transfer-manager.vala ../src/mconnect/transfer-manager-proxy.vala ../src/mconnect/transfer-interface.vala ../src/mconnect/transfer-proxy.vala ../src/mconnect/transfer-download.vala ../src/mconnect/transfer-upload.vala ../src/mconnect/logging.vala ../src/crypt/certificate.vala
../src/mconnect/core.vala:51.13-51.37: warning: unhandled error `GLib.Error'
            var cert = init_crypto ();
            ^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/utils.vala:117.13-117.74: warning: unhandled error `GLib.Error'
            var tls_serv = TlsServerConnection.@new (sock_conn, self_cert);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/utils.vala:123.50-123.80: warning: unhandled error `GLib.Error'
                                                 sock_conn.get_remote_address ());
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/utils.vala:122.24-123.81: warning: unhandled error `GLib.Error'
../src/mconnect/device.vala:168.21-169.86: warning: unhandled error `GLib.Error'
../src/mconnect/device.vala:620.13-620.25: warning: implicit .begin is deprecated
../src/mconnect/mousepad.vala:124.13-124.32: warning: Gdk.Display.get_pointer has been deprecated since 3.0
../src/mconnect/transfer-download.vala:159.9-159.28: warning: unhandled error `GLib.Error'
        this.file.@delete ();
        ^^^^^^^^^^^^^^^^^^^^
../src/mconnect/utils.vala:186.13-186.23: warning: `null' incompatible with return type `string[]'
            return null;
            ^^^^^^^^^^^
../src/mconnect/share.vala:108.13-108.54: warning: unhandled error `GLib.Error'
            AppInfo.launch_default_for_uri (url, null);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/transfer-upload.vala:74.19-74.44: warning: unhandled error `GLib.Error'
        var isa = conn.get_remote_address () as InetSocketAddress;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/share.vala:191.13-191.19: warning: unhandled error `GLib.Error'
            throw e;
            ^^^^^^^
../src/mconnect/mpris-proxies.vala:22.5-22.39: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract string[] list_names () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/mpris-proxies.vala:36.5-36.29: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void next () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/mpris-proxies.vala:37.5-37.33: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void previous () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/mpris-proxies.vala:38.5-38.35: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void play_pause () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/mpris-proxies.vala:39.5-39.29: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void seek (int64 Offset) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:71.5-71.23: error: Property `DeviceDBusProxy.allowed' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool allowed {
    ^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:79.5-79.25: error: Property `DeviceDBusProxy.is_active' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool is_active {
    ^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:63.5-63.25: error: Property `DeviceDBusProxy.is_paired' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool is_paired {
    ^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:27.5-27.20: error: Property `DeviceDBusProxy.id' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public string id {
    ^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:35.5-35.22: error: Property `DeviceDBusProxy.name' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public string name {
    ^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:43.5-43.29: error: Property `DeviceDBusProxy.device_type' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public string device_type {
    ^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:51.5-51.32: error: Property `DeviceDBusProxy.protocol_version' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public uint protocol_version {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:273.9-273.53: warning: unhandled error `GLib.IOError'
        handler.bus_register (conn, this.object_path);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/device-proxy.vala:284.13-284.41: warning: unhandled error `GLib.IOError'
            handler.bus_unregister (conn);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/share-proxy.vala:41.5-41.26: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void share_file (string path) throws IOError {
    ^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/share-proxy.vala:45.5-45.25: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void share_url (string url) throws IOError {
    ^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/share-proxy.vala:50.5-50.26: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void share_text (string text) throws IOError {
    ^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/telephony-proxy.vala:41.5-41.24: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void send_sms (string number, string message) {
    ^^^^^^^^^^^^^^^^^^^^
../src/mconnect/devicemanager-proxy.vala:158.13-158.53: warning: unhandled error `GLib.IOError'
            h.bus_register (this.bus, dp.object_path);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/devicemanager-proxy.vala:67.5-67.28: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void allow_device (string path) {
    ^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/devicemanager-proxy.vala:86.5-86.31: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void disallow_device (string path) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/devicemanager-proxy.vala:104.5-104.36: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public ObjectPath[] list_devices () {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/transfer-proxy.vala:39.28-39.72: warning: unhandled error `GLib.IOError'
        this.register_id = conn.register_object (this.object_path, this);
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/mconnect/transfer-proxy.vala:50.5-50.22: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void cancel () {
    ^^^^^^^^^^^^^^^^^^
../src/mconnect/transfer-manager-proxy.vala:52.5-52.33: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public ObjectPath[] list_jobs () {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 7 error(s), 30 warning(s)
ninja: build stopped: subcommand failed.
`

**Comment by petRUShka** [comment]
../src/mconnect/transfer-manager-proxy.vala:52.5-52.33: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public ObjectPath[] list_jobs () {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 7 error(s), 30 warning(s)
[11/57] Compiling C object 'mconnectctl@exe/meson-generated_src_mconnectctl_main.c.o'.
ninja: build stopped: subcommand failed.
